---
- name: Set up VM to run Selenium tests on Linux/Firefox environment
  hosts: linux_selenium_server
  become: True
  become_method: sudo
  environment:
    DISPLAY: ":99"
  vars:
    selenium_dir: /vagrant/src/test/resources
    selenium_jar: /opt/selenium/selenium.jar
  tasks:
    - name: Add Google Chrome key
      apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

    - name: Add Google Chrome repo
      copy: content="deb http://dl.google.com/linux/chrome/deb/ stable main" dest=/etc/apt/sources.list.d/google-chrome.list owner=root group=root mode=644
  
    - name: Install apt packages
      apt: pkg={{ item }} update_cache=yes
      with_items:
        - openjdk-8-jdk
        - unzip
        - firefox
        - daemon
        - xvfb
        - xorg
        - dbus-x11
        - xfonts-100dpi
        - xfonts-75dpi
        - xfonts-cyrillic
        - google-chrome-stable
   
    - name: Download Chrome driver and unzip into /usr/local/bin
      unarchive: src=http://chromedriver.storage.googleapis.com/2.27/chromedriver_linux64.zip dest=/usr/local/bin remote_src=yes
      
    - name: Download Gecko driver and unzip into /usr/local/bin
      unarchive: src=https://github.com/mozilla/geckodriver/releases/download/v0.12.0/geckodriver-v0.12.0-linux64.tar.gz dest=/usr/local/bin remote_src=yes
      
    - name: Create destination directory for Selenium jar
      file: name=/opt/selenium state=directory mode=0755
    
    - name: download selenium jar
      get_url: url="http://selenium-release.storage.googleapis.com/3.0/selenium-server-standalone-3.0.1.jar" dest={{ selenium_jar }}
    
    - name: Start Xvfb 
      shell: daemon -- Xvfb :99

    - name: Start Selenium hub
      shell: daemon -- java -jar {{ selenium_jar }} -role hub -hubConfig {{ selenium_dir }}/hub.json
      
    - name: Start Selenium Firefox node
      shell: daemon -- java -jar {{ selenium_jar }} -role node -nodeConfig {{ selenium_dir }}/firefox-linux.json
      
    - name: Start Selenium Chrome node
      shell: daemon -- java -jar {{ selenium_jar }} -role node -nodeConfig {{ selenium_dir }}/chrome-linux.json
