/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'joe' at '9/27/16 10:57 AM' with Gradle 2.13
 *
 * @author joe, @date 9/27/16 10:57 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
